### PR TITLE
Allow customization

### PR DESCRIPTION
**Pull request by CarliJoy**
Hi @sloria ,

thank you for the great extension for sphinx.
We want to use it with a custom gitlab instance (see #93), unfortunately github urls were hard coded in your version..

After looking inside the code I realized that with some modifications it could be handled much more flexible/customizable.

So I was so free to restructure the code a bit to allow proper customization.
Still the code remains fully backward compatible to existing settings.

Only exception is the commit role. To have a unified result it now also has the `@` prefix, even for same repro links.

I hope you are okay with the changes and agree with the structure.

Tests were also added for the new features.

Note: I included the user role logic within the IssueRole logic. The github changelog is a bit confusing there.

I tried to change the travis settings to work with Python 3.10 but as @hugovk figured out traivs sucks ;-)
I saw that  @hugovk  experimented with github actions, looks good.

PS: I noticed that you still use user/password login for PyPi. AFAIK this is no longer supported/not recommended (instead people should use project specific tokens).

PSS: I can recomment https://pyscaffold.org/en/stable/ to set up further projects. It uses setuptools-scm to set versions -> very helpful :-)

### CODE REVIEW

**Comment by CarliJoy** [comment]
FYI: https://app.travis-ci.com/github/CarliJoy/sphinx-issues

**Comment by sloria** [comment]
Thanks! This looks nice on an initial skim. I'll give this a closer look when i have more time off the clock

> PS: I noticed that you still use user/password login for PyPi. AFAIK this is no longer supported/not recommended (instead people should use project specific tokens).

yeah planning to fix this as part of #121 

> PSS: I can recomment https://pyscaffold.org/en/stable/ to set up further projects. It uses setuptools-scm to set versions -> very helpful :-

will take a look at that. i actually prefer explicit versioning to setuptools-scm, but maybe we can grab some other ideas from that project 🙂

**Comment by CarliJoy** [comment]
@sloria  merged it but you need to approve the pipelines.

**Comment by CarliJoy** [comment]
@sloria Just a ping to approve the Workflows again (fixed the merge conflict because of the version in the file change).
And also a kind request to consider reviewing the MR

**Comment by sloria** [comment]
Yes, I've not forgotten about this! Sorry for the delay...work and life got me busy this week. Will plan to review and merge this over the weekend.

**Review by sloria — APPROVED** [review]
Just made a few minor changes, but overall looks good. Thanks for the PR!

**Pull request merged**
